defaults:
  - all4one
  - _self_

name: "HPO-All4One-cifar100" # change here for cifar10
method: "hpo-all4one"
hpo_kwargs:
  hp_group_params:
    lr: 0.01
  hpo_params:
    algorithm: sgd
    regularization: 1
    ema:
      covs: 0.0
      stats: 0.99
    scale_gradients: 0.5
precision: 32-true
