defaults:
  - all4one
  - _self_

name: "HPO-All4One-imagenet-100"
method: "hpo-all4one"
method_kwargs:
  join_feature_loss: true
hpo_kwargs:
  weights_optimizer: adam
  hp_group_params:
    lr: 0.1
  hpo_params:
    algorithm: sgd
    encoder_decoder: true
    scale_gradients: 0.5
precision: 32-true
